//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEProcessor.HMM {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HMM.IHMM")]
    public interface IHMM {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHMM/GetData", ReplyAction="http://tempuri.org/IHMM/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHMM/Scan", ReplyAction="http://tempuri.org/IHMM/ScanResponse")]
        ProteinCoverageViewer.HMMService.HMMResult[] Scan(string fastaSequence);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHMMChannel : SEProcessor.HMM.IHMM, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HMMClient : System.ServiceModel.ClientBase<SEProcessor.HMM.IHMM>, SEProcessor.HMM.IHMM {
        
        public HMMClient() {
        }
        
        public HMMClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HMMClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HMMClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HMMClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public ProteinCoverageViewer.HMMService.HMMResult[] Scan(string fastaSequence) {
            return base.Channel.Scan(fastaSequence);
        }
    }
}
