//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpectrumViewer2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpectrumViewer2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 104.68946	319.8
        ///127.05116	2069
        ///127.08686	1971.6
        ///128.58667	342.2
        ///129.1031	751.1
        ///130.08827	473.8
        ///131.44409	284.9
        ///136.07626	1187.1
        ///141.06618	420
        ///144.07777	508.6
        ///145.06119	567.6
        ///147.1134	818.6
        ///155.04578	2078
        ///155.08215	1750.7
        ///155.11943	386.6
        ///167.11794	358.4
        ///172.07253	12209.6
        ///173.07686	593
        ///173.12885	1057.8
        ///175.07339	803.3
        ///175.12042	371.9
        ///195.11345	660.4
        ///197.05629	417.3
        ///198.08815	1574.1
        ///201.12421	7637.4
        ///202.129	682.9
        ///213.1243	593.4
        ///213.16339	382.5
        ///214.08263	801.4
        ///215.1152	2074.2
        ///217.08008	321.6
        ///217.54337	334.4
        ///224 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExampleSpectrum {
            get {
                return ResourceManager.GetString("ExampleSpectrum", resourceCulture);
            }
        }
    }
}
