//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEProcessor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<Parameters>\r\n  <LabeledDecoyTag>Reverse<" +
            "/LabeledDecoyTag>\r\n  <UnlabeledDecoyTag>Scrambled_0</UnlabeledDecoyTag>\r\n  <Elim" +
            "inateInPtns>true</EliminateInPtns>\r\n  <GroupPtnsWithXCommonPeptides>1</GroupPtns" +
            "WithXCommonPeptides>\r\n  <GroupByNoEnzymaticTermini>true</GroupByNoEnzymaticTermi" +
            "ni>\r\n  <GroupByChargeState>false</GroupByChargeState>\r\n  <MyEnzime>Trypsin</MyEn" +
            "zime>\r\n  <SpectraFDR>0.03</SpectraFDR>\r\n  <PeptideFDR>0.02</PeptideFDR>\r\n  <Prot" +
            "einFDR>0.01</ProteinFDR>\r\n  <CompositeScorePrimaryScore>true</CompositeScorePrim" +
            "aryScore>\r\n  <CompositeScoreSecondaryScore>false</CompositeScoreSecondaryScore>\r" +
            "\n  <CompositeScoreDeltaCN>true</CompositeScoreDeltaCN>\r\n  <CompositeScorePeaksMa" +
            "tched>true</CompositeScorePeaksMatched>\r\n  <CompositeScoreDeltaMassPPM>true</Com" +
            "positeScoreDeltaMassPPM>\r\n  <CompositScoreDigestion>false</CompositScoreDigestio" +
            "n>\r\n  <CompositeScorePresence>true</CompositeScorePresence>\r\n  <CompositeScoreSe" +
            "condaryRank>true</CompositeScoreSecondaryRank>\r\n  <AlternativeProteinDB />\r\n  <C" +
            "onsiderOnlyFirstDBLocus>false</ConsiderOnlyFirstDBLocus>\r\n  <SequenceFiltersEnab" +
            "led>false</SequenceFiltersEnabled>\r\n  <DeltaMassPPMPostProcessing>5</DeltaMassPP" +
            "MPostProcessing>\r\n  <MS2PPM>750</MS2PPM>\r\n  <SeqQFilterACount>0</SeqQFilterACoun" +
            "t>\r\n  <SeqQFilterBCount>2</SeqQFilterBCount>\r\n  <SeqQFilterCCount>0</SeqQFilterC" +
            "Count>\r\n  <SeqQFilterXCount>0</SeqQFilterXCount>\r\n  <SeqQFilterYCount>2</SeqQFil" +
            "terYCount>\r\n  <SeqQFilterZCount>0</SeqQFilterZCount>\r\n  <SeqQFilterCAXCount>0</S" +
            "eqQFilterCAXCount>\r\n  <SeqQFilterCBYCount>1</SeqQFilterCBYCount>\r\n  <SeqQFilterC" +
            "CZCount>0</SeqQFilterCCZCount>\r\n  <SeqQFilterRelativeIntensityThreshold>0.005</S" +
            "eqQFilterRelativeIntensityThreshold>\r\n  <QFilterMinSequenceLength>6</QFilterMinS" +
            "equenceLength>\r\n  <QFilterDiscardChargeOneMS>false</QFilterDiscardChargeOneMS>\r\n" +
            "  <QFilterDeltaMassPPM>true</QFilterDeltaMassPPM>\r\n  <QFilterDeltaMassPPMValue>3" +
            "0</QFilterDeltaMassPPMValue>\r\n  <QFilterPrimaryScore>false</QFilterPrimaryScore>" +
            "\r\n  <QFilterPrimaryScoreValue>1</QFilterPrimaryScoreValue>\r\n  <QFilterSecondaryS" +
            "core>false</QFilterSecondaryScore>\r\n  <QFilterSecondaryScoreValue>0</QFilterSeco" +
            "ndaryScoreValue>\r\n  <QFilterMinNoEnzymaticTermini>0</QFilterMinNoEnzymaticTermin" +
            "i>\r\n  <QFilterDiscardProteinsWithNoUniquePeptides>false</QFilterDiscardProteinsW" +
            "ithNoUniquePeptides>\r\n  <QFilterProteinsMinNoPeptides>1</QFilterProteinsMinNoPep" +
            "tides>\r\n  <QFilterMahalanobisDistance>false</QFilterMahalanobisDistance>\r\n  <QFi" +
            "lterMahalanobisDistanceValue>0</QFilterMahalanobisDistanceValue>\r\n  <QFilterMinS" +
            "pecCount>1</QFilterMinSpecCount>\r\n  <QFilterMinNoStates>1</QFilterMinNoStates>\r\n" +
            "  <QFilterMinPrimaryScoreForOneHitWonders>2.0</QFilterMinPrimaryScoreForOneHitWo" +
            "nders>\r\n  <QFilterMinPrimaryScoreForNonOneHitWonders>1.8</QFilterMinPrimaryScore" +
            "ForNonOneHitWonders>\r\n  <SeachResultDirectoy />\r\n  <FormsPriorForPeptides>false<" +
            "/FormsPriorForPeptides>\r\n  <QFilterDeltaCNMin>0.001</QFilterDeltaCNMin>\r\n  <QFil" +
            "terDeltaCN>true</QFilterDeltaCN>\r\n</Parameters>")]
        public string FilterSettings {
            get {
                return ((string)(this["FilterSettings"]));
            }
            set {
                this["FilterSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<Parameters>\r\n  <LabeledDecoyTag>Reverse<" +
            "/LabeledDecoyTag>\r\n  <UnlabeledDecoyTag>Scrambled_0</UnlabeledDecoyTag>\r\n  <Elim" +
            "inateInPtns>true</EliminateInPtns>\r\n  <GroupPtnsWithXCommonPeptides>1</GroupPtns" +
            "WithXCommonPeptides>\r\n  <GroupByNoEnzymaticTermini>true</GroupByNoEnzymaticTermi" +
            "ni>\r\n  <GroupByChargeState>false</GroupByChargeState>\r\n  <MyEnzime>Trypsin</MyEn" +
            "zime>\r\n  <SpectraFDR>0.03</SpectraFDR>\r\n  <PeptideFDR>0.02</PeptideFDR>\r\n  <Prot" +
            "einFDR>0.01</ProteinFDR>\r\n  <CompositeScorePrimaryScore>true</CompositeScorePrim" +
            "aryScore>\r\n  <CompositeScoreSecondaryScore>false</CompositeScoreSecondaryScore>\r" +
            "\n  <CompositeScoreDeltaCN>true</CompositeScoreDeltaCN>\r\n  <CompositeScorePeaksMa" +
            "tched>true</CompositeScorePeaksMatched>\r\n  <CompositeScoreDeltaMassPPM>true</Com" +
            "positeScoreDeltaMassPPM>\r\n  <CompositScoreDigestion>false</CompositScoreDigestio" +
            "n>\r\n  <CompositeScorePresence>true</CompositeScorePresence>\r\n  <CompositeScoreSe" +
            "condaryRank>true</CompositeScoreSecondaryRank>\r\n  <AlternativeProteinDB />\r\n  <C" +
            "onsiderOnlyFirstDBLocus>false</ConsiderOnlyFirstDBLocus>\r\n  <SequenceFiltersEnab" +
            "led>false</SequenceFiltersEnabled>\r\n  <DeltaMassPPMPostProcessing>10</DeltaMassP" +
            "PMPostProcessing>\r\n  <MS2PPM>750</MS2PPM>\r\n  <SeqQFilterACount>0</SeqQFilterACou" +
            "nt>\r\n  <SeqQFilterBCount>2</SeqQFilterBCount>\r\n  <SeqQFilterCCount>0</SeqQFilter" +
            "CCount>\r\n  <SeqQFilterXCount>0</SeqQFilterXCount>\r\n  <SeqQFilterYCount>2</SeqQFi" +
            "lterYCount>\r\n  <SeqQFilterZCount>0</SeqQFilterZCount>\r\n  <SeqQFilterCAXCount>0</" +
            "SeqQFilterCAXCount>\r\n  <SeqQFilterCBYCount>1</SeqQFilterCBYCount>\r\n  <SeqQFilter" +
            "CCZCount>0</SeqQFilterCCZCount>\r\n  <SeqQFilterRelativeIntensityThreshold>0.005</" +
            "SeqQFilterRelativeIntensityThreshold>\r\n  <QFilterMinSequenceLength>6</QFilterMin" +
            "SequenceLength>\r\n  <QFilterDiscardChargeOneMS>false</QFilterDiscardChargeOneMS>\r" +
            "\n  <QFilterDeltaMassPPM>true</QFilterDeltaMassPPM>\r\n  <QFilterDeltaMassPPMValue>" +
            "30</QFilterDeltaMassPPMValue>\r\n  <QFilterPrimaryScore>false</QFilterPrimaryScore" +
            ">\r\n  <QFilterPrimaryScoreValue>1</QFilterPrimaryScoreValue>\r\n  <QFilterSecondary" +
            "Score>false</QFilterSecondaryScore>\r\n  <QFilterSecondaryScoreValue>0</QFilterSec" +
            "ondaryScoreValue>\r\n  <QFilterMinNoEnzymaticTermini>0</QFilterMinNoEnzymaticTermi" +
            "ni>\r\n  <QFilterDiscardProteinsWithNoUniquePeptides>false</QFilterDiscardProteins" +
            "WithNoUniquePeptides>\r\n  <QFilterProteinsMinNoPeptides>1</QFilterProteinsMinNoPe" +
            "ptides>\r\n  <QFilterMahalanobisDistance>false</QFilterMahalanobisDistance>\r\n  <QF" +
            "ilterMahalanobisDistanceValue>0</QFilterMahalanobisDistanceValue>\r\n  <QFilterMin" +
            "SpecCount>1</QFilterMinSpecCount>\r\n  <QFilterMinNoStates>1</QFilterMinNoStates>\r" +
            "\n  <QFilterMinPrimaryScoreForOneHitWonders>2.0</QFilterMinPrimaryScoreForOneHitW" +
            "onders>\r\n  <QFilterMinPrimaryScoreForNonOneHitWonders>1.8</QFilterMinPrimaryScor" +
            "eForNonOneHitWonders>\r\n  <SeachResultDirectoy />\r\n  <FormsPriorForPeptides>false" +
            "</FormsPriorForPeptides>\r\n  <QFilterDeltaCNMin>0.001</QFilterDeltaCNMin>\r\n  <QFi" +
            "lterDeltaCN>true</QFilterDeltaCN>\r\n</Parameters>")]
        public string FilterSettingsHL {
            get {
                return ((string)(this["FilterSettingsHL"]));
            }
            set {
                this["FilterSettingsHL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<Parameters>\r\n  <LabeledDecoyTag>Reverse<" +
            "/LabeledDecoyTag>\r\n  <UnlabeledDecoyTag>Scrambled_0</UnlabeledDecoyTag>\r\n  <Elim" +
            "inateInPtns>true</EliminateInPtns>\r\n  <GroupPtnsWithXCommonPeptides>1</GroupPtns" +
            "WithXCommonPeptides>\r\n  <GroupByNoEnzymaticTermini>true</GroupByNoEnzymaticTermi" +
            "ni>\r\n  <GroupByChargeState>false</GroupByChargeState>\r\n  <MyEnzime>Trypsin</MyEn" +
            "zime>\r\n  <SpectraFDR>0.03</SpectraFDR>\r\n  <PeptideFDR>0.02</PeptideFDR>\r\n  <Prot" +
            "einFDR>0.01</ProteinFDR>\r\n  <CompositeScorePrimaryScore>true</CompositeScorePrim" +
            "aryScore>\r\n  <CompositeScoreSecondaryScore>false</CompositeScoreSecondaryScore>\r" +
            "\n  <CompositeScoreDeltaCN>true</CompositeScoreDeltaCN>\r\n  <CompositeScorePeaksMa" +
            "tched>true</CompositeScorePeaksMatched>\r\n  <CompositeScoreDeltaMassPPM>false</Co" +
            "mpositeScoreDeltaMassPPM>\r\n  <CompositScoreDigestion>false</CompositScoreDigesti" +
            "on>\r\n  <CompositeScorePresence>true</CompositeScorePresence>\r\n  <CompositeScoreS" +
            "econdaryRank>true</CompositeScoreSecondaryRank>\r\n  <AlternativeProteinDB />\r\n  <" +
            "ConsiderOnlyFirstDBLocus>false</ConsiderOnlyFirstDBLocus>\r\n  <SequenceFiltersEna" +
            "bled>false</SequenceFiltersEnabled>\r\n  <DeltaMassPPMPostProcessing>10</DeltaMass" +
            "PPMPostProcessing>\r\n  <MS2PPM>850</MS2PPM>\r\n  <SeqQFilterACount>0</SeqQFilterACo" +
            "unt>\r\n  <SeqQFilterBCount>2</SeqQFilterBCount>\r\n  <SeqQFilterCCount>0</SeqQFilte" +
            "rCCount>\r\n  <SeqQFilterXCount>0</SeqQFilterXCount>\r\n  <SeqQFilterYCount>2</SeqQF" +
            "ilterYCount>\r\n  <SeqQFilterZCount>0</SeqQFilterZCount>\r\n  <SeqQFilterCAXCount>0<" +
            "/SeqQFilterCAXCount>\r\n  <SeqQFilterCBYCount>1</SeqQFilterCBYCount>\r\n  <SeqQFilte" +
            "rCCZCount>0</SeqQFilterCCZCount>\r\n  <SeqQFilterRelativeIntensityThreshold>0.005<" +
            "/SeqQFilterRelativeIntensityThreshold>\r\n  <QFilterMinSequenceLength>6</QFilterMi" +
            "nSequenceLength>\r\n  <QFilterDiscardChargeOneMS>false</QFilterDiscardChargeOneMS>" +
            "\r\n  <QFilterDeltaMassPPM>false</QFilterDeltaMassPPM>\r\n  <QFilterDeltaMassPPMValu" +
            "e>30</QFilterDeltaMassPPMValue>\r\n  <QFilterPrimaryScore>false</QFilterPrimarySco" +
            "re>\r\n  <QFilterPrimaryScoreValue>1</QFilterPrimaryScoreValue>\r\n  <QFilterSeconda" +
            "ryScore>false</QFilterSecondaryScore>\r\n  <QFilterSecondaryScoreValue>0</QFilterS" +
            "econdaryScoreValue>\r\n  <QFilterMinNoEnzymaticTermini>0</QFilterMinNoEnzymaticTer" +
            "mini>\r\n  <QFilterDiscardProteinsWithNoUniquePeptides>false</QFilterDiscardProtei" +
            "nsWithNoUniquePeptides>\r\n  <QFilterProteinsMinNoPeptides>1</QFilterProteinsMinNo" +
            "Peptides>\r\n  <QFilterMahalanobisDistance>false</QFilterMahalanobisDistance>\r\n  <" +
            "QFilterMahalanobisDistanceValue>0</QFilterMahalanobisDistanceValue>\r\n  <QFilterM" +
            "inSpecCount>1</QFilterMinSpecCount>\r\n  <QFilterMinNoStates>1</QFilterMinNoStates" +
            ">\r\n  <QFilterMinPrimaryScoreForOneHitWonders>2</QFilterMinPrimaryScoreForOneHitW" +
            "onders>\r\n  <QFilterMinPrimaryScoreForNonOneHitWonders>1.8</QFilterMinPrimaryScor" +
            "eForNonOneHitWonders>\r\n  <SeachResultDirectoy />\r\n  <FormsPriorForPeptides>false" +
            "</FormsPriorForPeptides>\r\n  <QFilterDeltaCNMin>0.001</QFilterDeltaCNMin>\r\n  <QFi" +
            "lterDeltaCN>true</QFilterDeltaCN>\r\n</Parameters>")]
        public string FilterSettingsLL {
            get {
                return ((string)(this["FilterSettingsLL"]));
            }
            set {
                this["FilterSettingsLL"] = value;
            }
        }
    }
}
